apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: camelk
  labels:
    prometheus: k8s
spec:
  replicas: 1
  serviceAccountName: prometheus-k8s
  securityContext: {}
  serviceMonitorSelector: {}
  ruleSelector: {}
